[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SCION HTTP Proxy"
authors = [{name = "ETH Zürich", email = "jordi.subiranieto@inf.ethz.ch"}]
dynamic = ["version", "description"]
